### PR TITLE
Update dependencies and mark as isolating for APT

### LINKED ISSUE #106: Processor assumes annotations are on the classpath
With AutoValue 1.6, the annotations are no longer part of the AutoValue processor and are in a separate dependency, `auto-value-annotations`. This processor assumes that these types will be present and so when updating to 1.6, a NoClassDefFoundException is thrown.

```
Caused by: java.lang.NoClassDefFoundError: com/google/auto/value/AutoValue
        at com.ryanharter.auto.value.moshi.AutoValueMoshiAdapterFactoryProcessor.getSupportedAnnotationTypes(AutoValueMoshiAdapterFactoryProcessor.java:61)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:505)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 58 more
Caused by: java.lang.ClassNotFoundException: com.google.auto.value.AutoValue
        ... 68 more
```

The processor should either declare a dependency on `auto-value-annotations` or migrate away from referencing the `@AutoValue` by class and instead look it up via FQCN or `Types`/`Elements`.

### LINKED ISSUE #112: Add support for incremental annotation processing by implementing new AutoValueExtension API
Auto Value supports incremental annotation processing in 1.6.3-rc1. auto-value-moshi can implement new API to support incremental annotation processing.

### PR DESCRIPTION
**Pull request by ZacSweers**
Resolves a few things:

Resolves #112
Resolves #106

### CODE REVIEW

**Review by rharter — APPROVED** [review]
Looks great! Thanks!

**Comment by tbroyer** [comment]
Extension doesn't implement the new API to be marked as isolating.

Also, have you tested incrementality of the processor? It doesn't look like it declares originating elements for the generated sources, which is at least required for isolating processors (not sure about aggregating ones).

**Comment by ZacSweers** [comment]
that's... really strange o_O. I had it locally for sure, probably got lost in the bouncing around of repos.

For the processor - I was under the impression that aggregating processors didn't have to declare originating elements (since they could be from many places). I'll read up on the docs again

**Comment by ZacSweers** [comment]
I suppose that's implied here - https://docs.gradle.org/current/userguide/java_plugin.html

It just says isolating must have one, but doesn't specify anything explicitly for aggregating ones. Do you know if we also need to declare the annotated factory interface itself as an originating element? (Assuming yes)

Also - would extensions such as `@Memoized` imply that its extension should be aggregating since it depends on annotations outside of what's fetched in roundenvironment?

**Comment by ZacSweers** [comment]
I've added the missing bits in https://github.com/rharter/auto-value-moshi/pull/114 if you want to review
